version: '3'
services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"
  mariadb:
    image: 'mariadb:10.4'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
    - "3306:3306"